version: "3.5"
services: 
  web:
    container_name: web_go_server
    build:
      context: .
      dockerfile: .docker/Dockerfile
    image: goby
    entrypoint: /dev-entrypoint.sh
    environment: 
      - ENVIRONMENT=dev
    ports: 
      - 7081:80
    volumes: 
      - ./src:/go/src/bitbucket.org/goby
    